[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # 安全头
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://cdnjs.cloudflare.com https://cdn.jsdelivr.net;
      style-src 'self' https://fonts.googleapis.com 'unsafe-inline';
      font-src 'self' https://fonts.gstatic.com;
      media-src 'self';
      connect-src 'none';
      object-src 'none';
      base-uri 'self';
      form-action 'none';
    """
